import type { Metadata } from 'next';
import './globals.css';
import classes from './layout.module.scss';
import ActionBar from '@/components/Nav/ActionBar';
import NextAuthProvider from '@/components/Auth/NextAuthProvider';
import Footer from '@/components/Footer/Footer';
import { getUserData } from '@/lib/actions/utils/getUserData';
import seedDatabase from '@/lib/actions/utils/seedDatabase';

export const metadata: Metadata = {
	title: 'Social Media App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const { session, user } = await getUserData('theme name image id imageType');

	return (
		<html lang="en">
			<body data-theme={user ? user.theme : ''}>
				<div>
					<div id="overlay-root"></div>
					{session && (
						<ActionBar
							name={user.name}
							image={user.image}
							userId={user.id}
							imageType={user.imageType}
						/>
					)}
					<div className={session ? classes.main : ''}>
						<main>
							<NextAuthProvider>{children}</NextAuthProvider>
						</main>
						<Footer />
					</div>
				</div>
			</body>
		</html>
	);
}
