import type { Metadata } from 'next';
import './globals.css';
import classes from './layout.module.scss';
import { getServerSession } from 'next-auth';
import ActionBar from '@/components/Nav/ActionBar';
import NextAuthProvider from '@/components/Auth/NextAuthProvider';
import { cookies } from 'next/headers';
import Footer from '@/components/Footer/Footer';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await getServerSession();

	let theme;
	if (session) {
		theme = cookies().get('theme')!.value;
	}

	return (
		<html lang="en">
			<body data-theme={theme}>
				<div>
					{session && <ActionBar />}
					<main className={session ? classes.main : ''}>
						<NextAuthProvider>{children}</NextAuthProvider>
					</main>
					{/* <Footer /> */}
				</div>
			</body>
		</html>
	);
}
